[package]
name = "ncn-ledger"
version = "0.4.0-40100"
edition = "2021"

[dependencies]
agave-snapshots               = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-accounts-db            = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-runtime                = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-ledger                 = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-rpc                    = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-geyser-plugin-manager  = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-unified-scheduler-pool = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-genesis-utils          = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-measure                = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-clap-utils             = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-genesis-config         = "4.0.0"
solana-metrics                = "4.1.0"
solana-program = { version = "4.0.0", default-features = false, features = [] }
solana-sdk = "=4.0.1"
solana-stake-interface = { version = "3.1.0", features = ["sysvar", "serde"] }
clap_old = { package = "clap", version = "2.33.1" }
crossbeam-channel = "0.5.15"
libc = "0.2"
log = "0.4.22"
thiserror = "2.0"
tokio = { version = "1.36.0", features = ["full"] }
