/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithPayer,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type ExtendedClient,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/program-client-core";
import {
  getBallotBoxCodec,
  getConsensusResultCodec,
  getMetaMerkleProofCodec,
  getProgramConfigCodec,
  type BallotBox,
  type BallotBoxArgs,
  type ConsensusResult,
  type ConsensusResultArgs,
  type MetaMerkleProof,
  type MetaMerkleProofArgs,
  type ProgramConfig,
  type ProgramConfigArgs,
} from "../accounts";
import {
  getCastVoteInstruction,
  getCloseMetaMerkleProofInstruction,
  getFinalizeBallotInstruction,
  getFinalizeProposedAuthorityInstruction,
  getInitBallotBoxInstructionAsync,
  getInitMetaMerkleProofInstruction,
  getInitProgramConfigInstructionAsync,
  getRemoveVoteInstruction,
  getResetBallotBoxInstruction,
  getSetTieBreakerInstruction,
  getUpdateOperatorWhitelistInstruction,
  getUpdateProgramConfigInstruction,
  getVerifyMerkleProofInstruction,
  parseCastVoteInstruction,
  parseCloseMetaMerkleProofInstruction,
  parseFinalizeBallotInstruction,
  parseFinalizeProposedAuthorityInstruction,
  parseInitBallotBoxInstruction,
  parseInitMetaMerkleProofInstruction,
  parseInitProgramConfigInstruction,
  parseRemoveVoteInstruction,
  parseResetBallotBoxInstruction,
  parseSetTieBreakerInstruction,
  parseUpdateOperatorWhitelistInstruction,
  parseUpdateProgramConfigInstruction,
  parseVerifyMerkleProofInstruction,
  type CastVoteInput,
  type CloseMetaMerkleProofInput,
  type FinalizeBallotInput,
  type FinalizeProposedAuthorityInput,
  type InitBallotBoxAsyncInput,
  type InitMetaMerkleProofInput,
  type InitProgramConfigAsyncInput,
  type ParsedCastVoteInstruction,
  type ParsedCloseMetaMerkleProofInstruction,
  type ParsedFinalizeBallotInstruction,
  type ParsedFinalizeProposedAuthorityInstruction,
  type ParsedInitBallotBoxInstruction,
  type ParsedInitMetaMerkleProofInstruction,
  type ParsedInitProgramConfigInstruction,
  type ParsedRemoveVoteInstruction,
  type ParsedResetBallotBoxInstruction,
  type ParsedSetTieBreakerInstruction,
  type ParsedUpdateOperatorWhitelistInstruction,
  type ParsedUpdateProgramConfigInstruction,
  type ParsedVerifyMerkleProofInstruction,
  type RemoveVoteInput,
  type ResetBallotBoxInput,
  type SetTieBreakerInput,
  type UpdateOperatorWhitelistInput,
  type UpdateProgramConfigInput,
  type VerifyMerkleProofInput,
} from "../instructions";
import {
  findBallotBoxPda,
  findMetaMerkleProofPda,
  findProgramConfigPda,
} from "../pdas";

export const NCN_SNAPSHOT_PROGRAM_ADDRESS =
  "ncnwF8AgynRcdEnGLcprSQNaKvgSMTgk3yPRc8cf9Zf" as Address<"ncnwF8AgynRcdEnGLcprSQNaKvgSMTgk3yPRc8cf9Zf">;

export enum NcnSnapshotAccount {
  BallotBox,
  ConsensusResult,
  MetaMerkleProof,
  ProgramConfig,
}

export function identifyNcnSnapshotAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): NcnSnapshotAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 169, 156, 8, 92, 14, 24, 101]),
      ),
      0,
    )
  ) {
    return NcnSnapshotAccount.BallotBox;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([105, 121, 122, 243, 100, 58, 93, 161]),
      ),
      0,
    )
  ) {
    return NcnSnapshotAccount.ConsensusResult;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([130, 55, 141, 26, 195, 58, 18, 178]),
      ),
      0,
    )
  ) {
    return NcnSnapshotAccount.MetaMerkleProof;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([196, 210, 90, 231, 144, 149, 140, 63]),
      ),
      0,
    )
  ) {
    return NcnSnapshotAccount.ProgramConfig;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "ncnSnapshot" },
  );
}

export enum NcnSnapshotInstruction {
  CastVote,
  CloseMetaMerkleProof,
  FinalizeBallot,
  FinalizeProposedAuthority,
  InitBallotBox,
  InitMetaMerkleProof,
  InitProgramConfig,
  RemoveVote,
  ResetBallotBox,
  SetTieBreaker,
  UpdateOperatorWhitelist,
  UpdateProgramConfig,
  VerifyMerkleProof,
}

export function identifyNcnSnapshotInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): NcnSnapshotInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([20, 212, 15, 189, 69, 180, 69, 151]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.CastVote;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([248, 239, 182, 146, 23, 215, 172, 3]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.CloseMetaMerkleProof;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([212, 43, 85, 58, 158, 34, 41, 42]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.FinalizeBallot;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([89, 96, 108, 130, 223, 223, 213, 102]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.FinalizeProposedAuthority;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([164, 20, 45, 213, 67, 43, 193, 212]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.InitBallotBox;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([190, 210, 132, 165, 204, 88, 110, 84]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.InitMetaMerkleProof;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([185, 54, 237, 229, 219, 179, 109, 20]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.InitProgramConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([32, 187, 23, 3, 156, 232, 55, 177]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.RemoveVote;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([108, 127, 131, 171, 226, 219, 67, 163]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.ResetBallotBox;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([228, 10, 240, 130, 193, 58, 103, 181]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.SetTieBreaker;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([25, 65, 144, 150, 200, 245, 156, 92]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.UpdateOperatorWhitelist;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([214, 3, 187, 98, 170, 106, 33, 45]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.UpdateProgramConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([51, 191, 37, 169, 74, 207, 201, 102]),
      ),
      0,
    )
  ) {
    return NcnSnapshotInstruction.VerifyMerkleProof;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "ncnSnapshot" },
  );
}

export type ParsedNcnSnapshotInstruction<
  TProgram extends string = "ncnwF8AgynRcdEnGLcprSQNaKvgSMTgk3yPRc8cf9Zf",
> =
  | ({
      instructionType: NcnSnapshotInstruction.CastVote;
    } & ParsedCastVoteInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.CloseMetaMerkleProof;
    } & ParsedCloseMetaMerkleProofInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.FinalizeBallot;
    } & ParsedFinalizeBallotInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.FinalizeProposedAuthority;
    } & ParsedFinalizeProposedAuthorityInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.InitBallotBox;
    } & ParsedInitBallotBoxInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.InitMetaMerkleProof;
    } & ParsedInitMetaMerkleProofInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.InitProgramConfig;
    } & ParsedInitProgramConfigInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.RemoveVote;
    } & ParsedRemoveVoteInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.ResetBallotBox;
    } & ParsedResetBallotBoxInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.SetTieBreaker;
    } & ParsedSetTieBreakerInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.UpdateOperatorWhitelist;
    } & ParsedUpdateOperatorWhitelistInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.UpdateProgramConfig;
    } & ParsedUpdateProgramConfigInstruction<TProgram>)
  | ({
      instructionType: NcnSnapshotInstruction.VerifyMerkleProof;
    } & ParsedVerifyMerkleProofInstruction<TProgram>);

export function parseNcnSnapshotInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedNcnSnapshotInstruction<TProgram> {
  const instructionType = identifyNcnSnapshotInstruction(instruction);
  switch (instructionType) {
    case NcnSnapshotInstruction.CastVote: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.CastVote,
        ...parseCastVoteInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.CloseMetaMerkleProof: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.CloseMetaMerkleProof,
        ...parseCloseMetaMerkleProofInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.FinalizeBallot: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.FinalizeBallot,
        ...parseFinalizeBallotInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.FinalizeProposedAuthority: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.FinalizeProposedAuthority,
        ...parseFinalizeProposedAuthorityInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.InitBallotBox: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.InitBallotBox,
        ...parseInitBallotBoxInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.InitMetaMerkleProof: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.InitMetaMerkleProof,
        ...parseInitMetaMerkleProofInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.InitProgramConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.InitProgramConfig,
        ...parseInitProgramConfigInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.RemoveVote: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.RemoveVote,
        ...parseRemoveVoteInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.ResetBallotBox: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.ResetBallotBox,
        ...parseResetBallotBoxInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.SetTieBreaker: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.SetTieBreaker,
        ...parseSetTieBreakerInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.UpdateOperatorWhitelist: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.UpdateOperatorWhitelist,
        ...parseUpdateOperatorWhitelistInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.UpdateProgramConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.UpdateProgramConfig,
        ...parseUpdateProgramConfigInstruction(instruction),
      };
    }
    case NcnSnapshotInstruction.VerifyMerkleProof: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: NcnSnapshotInstruction.VerifyMerkleProof,
        ...parseVerifyMerkleProofInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "ncnSnapshot",
        },
      );
  }
}

export type NcnSnapshotPlugin = {
  accounts: NcnSnapshotPluginAccounts;
  instructions: NcnSnapshotPluginInstructions;
  pdas: NcnSnapshotPluginPdas;
  identifyAccount: typeof identifyNcnSnapshotAccount;
  identifyInstruction: typeof identifyNcnSnapshotInstruction;
  parseInstruction: typeof parseNcnSnapshotInstruction;
};

export type NcnSnapshotPluginAccounts = {
  ballotBox: ReturnType<typeof getBallotBoxCodec> &
    SelfFetchFunctions<BallotBoxArgs, BallotBox>;
  consensusResult: ReturnType<typeof getConsensusResultCodec> &
    SelfFetchFunctions<ConsensusResultArgs, ConsensusResult>;
  metaMerkleProof: ReturnType<typeof getMetaMerkleProofCodec> &
    SelfFetchFunctions<MetaMerkleProofArgs, MetaMerkleProof>;
  programConfig: ReturnType<typeof getProgramConfigCodec> &
    SelfFetchFunctions<ProgramConfigArgs, ProgramConfig>;
};

export type NcnSnapshotPluginInstructions = {
  castVote: (
    input: CastVoteInput,
  ) => ReturnType<typeof getCastVoteInstruction> & SelfPlanAndSendFunctions;
  closeMetaMerkleProof: (
    input: MakeOptional<CloseMetaMerkleProofInput, "payer">,
  ) => ReturnType<typeof getCloseMetaMerkleProofInstruction> &
    SelfPlanAndSendFunctions;
  finalizeBallot: (
    input: MakeOptional<FinalizeBallotInput, "payer">,
  ) => ReturnType<typeof getFinalizeBallotInstruction> &
    SelfPlanAndSendFunctions;
  finalizeProposedAuthority: (
    input: FinalizeProposedAuthorityInput,
  ) => ReturnType<typeof getFinalizeProposedAuthorityInstruction> &
    SelfPlanAndSendFunctions;
  initBallotBox: (
    input: MakeOptional<InitBallotBoxAsyncInput, "payer">,
  ) => ReturnType<typeof getInitBallotBoxInstructionAsync> &
    SelfPlanAndSendFunctions;
  initMetaMerkleProof: (
    input: MakeOptional<InitMetaMerkleProofInput, "payer">,
  ) => ReturnType<typeof getInitMetaMerkleProofInstruction> &
    SelfPlanAndSendFunctions;
  initProgramConfig: (
    input: MakeOptional<InitProgramConfigAsyncInput, "payer">,
  ) => ReturnType<typeof getInitProgramConfigInstructionAsync> &
    SelfPlanAndSendFunctions;
  removeVote: (
    input: RemoveVoteInput,
  ) => ReturnType<typeof getRemoveVoteInstruction> & SelfPlanAndSendFunctions;
  resetBallotBox: (
    input: ResetBallotBoxInput,
  ) => ReturnType<typeof getResetBallotBoxInstruction> &
    SelfPlanAndSendFunctions;
  setTieBreaker: (
    input: SetTieBreakerInput,
  ) => ReturnType<typeof getSetTieBreakerInstruction> &
    SelfPlanAndSendFunctions;
  updateOperatorWhitelist: (
    input: UpdateOperatorWhitelistInput,
  ) => ReturnType<typeof getUpdateOperatorWhitelistInstruction> &
    SelfPlanAndSendFunctions;
  updateProgramConfig: (
    input: UpdateProgramConfigInput,
  ) => ReturnType<typeof getUpdateProgramConfigInstruction> &
    SelfPlanAndSendFunctions;
  verifyMerkleProof: (
    input: VerifyMerkleProofInput,
  ) => ReturnType<typeof getVerifyMerkleProofInstruction> &
    SelfPlanAndSendFunctions;
};

export type NcnSnapshotPluginPdas = {
  ballotBox: typeof findBallotBoxPda;
  programConfig: typeof findProgramConfigPda;
  metaMerkleProof: typeof findMetaMerkleProofPda;
};

export type NcnSnapshotPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithPayer &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function ncnSnapshotProgram() {
  return <T extends NcnSnapshotPluginRequirements>(
    client: T,
  ): ExtendedClient<T, { ncnSnapshot: NcnSnapshotPlugin }> => {
    return extendClient(client, {
      ncnSnapshot: <NcnSnapshotPlugin>{
        accounts: {
          ballotBox: addSelfFetchFunctions(client, getBallotBoxCodec()),
          consensusResult: addSelfFetchFunctions(
            client,
            getConsensusResultCodec(),
          ),
          metaMerkleProof: addSelfFetchFunctions(
            client,
            getMetaMerkleProofCodec(),
          ),
          programConfig: addSelfFetchFunctions(client, getProgramConfigCodec()),
        },
        instructions: {
          castVote: (input) =>
            addSelfPlanAndSendFunctions(client, getCastVoteInstruction(input)),
          closeMetaMerkleProof: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCloseMetaMerkleProofInstruction({
                ...input,
                payer: input.payer ?? client.payer.address,
              }),
            ),
          finalizeBallot: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getFinalizeBallotInstruction({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          finalizeProposedAuthority: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getFinalizeProposedAuthorityInstruction(input),
            ),
          initBallotBox: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitBallotBoxInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          initMetaMerkleProof: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitMetaMerkleProofInstruction({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          initProgramConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitProgramConfigInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          removeVote: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRemoveVoteInstruction(input),
            ),
          resetBallotBox: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getResetBallotBoxInstruction(input),
            ),
          setTieBreaker: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetTieBreakerInstruction(input),
            ),
          updateOperatorWhitelist: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateOperatorWhitelistInstruction(input),
            ),
          updateProgramConfig: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateProgramConfigInstruction(input),
            ),
          verifyMerkleProof: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getVerifyMerkleProofInstruction(input),
            ),
        },
        pdas: {
          ballotBox: findBallotBoxPda,
          programConfig: findProgramConfigPda,
          metaMerkleProof: findMetaMerkleProofPda,
        },
        identifyAccount: identifyNcnSnapshotAccount,
        identifyInstruction: identifyNcnSnapshotInstruction,
        parseInstruction: parseNcnSnapshotInstruction,
      },
    });
  };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
