[package]
name = "cli"
version = "0.4.0-40100"
edition = "2021"

[dependencies]
anchor-client = "0.31.1"
clap = { version = "4", features = ["derive", "env"] }
ncn-ledger = { path = "../ledger" }
ncn-merkle-tree = { path = "../merkle-tree" }
solana-accounts-db            = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-runtime                = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-vote                   = { version = "4.1.2", features = ["agave-unstable-api"] }
solana-vote-program           = { version = "4.1.2", default-features = false, features = ["agave-unstable-api"] }
solana-program = { version = "4.0.0", default-features = false, features = [] }
solana-sdk = "=4.0.1"
solana-stake-interface = { version = "3.1.0", features = ["sysvar", "serde"] }
bincode = "1.3"
anchor-lang = "0.31.1"
log = "0.4.22"
env_logger = "0.10.2"
flate2 = "1.0"
tokio = { version = "1.36.0", features = ["full"] }
anyhow = "1.0.86"
im = "15.1"
borsh = { version = "0.10.3" }
ncn-snapshot = { path = "../programs/ncn-snapshot" }
squads-client = { path = "../../squads-client" }
spl-stake-pool = { version = "2.0.0", default-features = false, features = ["no-entrypoint"] }
borsh_stake = { package = "borsh", version = "1.5", default-features = false }

[dev-dependencies]
tempfile = "3"
