[package]
name = "ncn-snapshot"
version = "0.4.0-40100"
description = "Governance NCN Voting Program"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/solana-foundation/solana-governance"

[lib]
crate-type = ["cdylib", "lib"]
name = "ncn_snapshot"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]


[dependencies]
anchor-lang = "0.31.1"
