/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findGlobalConfigPda } from "../pdas";
import { SVMGOV_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const INITIALIZE_CONFIG_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([208, 127, 21, 1, 194, 190, 196, 70]);

export function getInitializeConfigDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_CONFIG_DISCRIMINATOR,
  );
}

export type InitializeConfigInstruction<
  TProgram extends string = typeof SVMGOV_PROGRAM_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountGlobalConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountProgram extends string | AccountMeta<string> =
    "govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU",
  TAccountProgramData extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountGlobalConfig extends string
        ? WritableAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      TAccountProgramData extends string
        ? ReadonlyAccount<TAccountProgramData>
        : TAccountProgramData,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  maxTitleLength: number;
  maxDescriptionLength: number;
  maxSupportEpochs: bigint;
  minProposalStakeLamports: bigint;
  clusterSupportPctMinBps: bigint;
  discussionEpochs: bigint;
  votingEpochs: bigint;
  snapshotEpochExtension: bigint;
  snapshotSlotOffset: bigint;
  maxSupporters: number;
};

export type InitializeConfigInstructionDataArgs = {
  maxTitleLength: number;
  maxDescriptionLength: number;
  maxSupportEpochs: number | bigint;
  minProposalStakeLamports: number | bigint;
  clusterSupportPctMinBps: number | bigint;
  discussionEpochs: number | bigint;
  votingEpochs: number | bigint;
  snapshotEpochExtension: number | bigint;
  snapshotSlotOffset: number | bigint;
  maxSupporters: number;
};

export function getInitializeConfigInstructionDataEncoder(): FixedSizeEncoder<InitializeConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["maxTitleLength", getU16Encoder()],
      ["maxDescriptionLength", getU16Encoder()],
      ["maxSupportEpochs", getU64Encoder()],
      ["minProposalStakeLamports", getU64Encoder()],
      ["clusterSupportPctMinBps", getU64Encoder()],
      ["discussionEpochs", getU64Encoder()],
      ["votingEpochs", getU64Encoder()],
      ["snapshotEpochExtension", getU64Encoder()],
      ["snapshotSlotOffset", getI64Encoder()],
      ["maxSupporters", getU32Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_CONFIG_DISCRIMINATOR }),
  );
}

export function getInitializeConfigInstructionDataDecoder(): FixedSizeDecoder<InitializeConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["maxTitleLength", getU16Decoder()],
    ["maxDescriptionLength", getU16Decoder()],
    ["maxSupportEpochs", getU64Decoder()],
    ["minProposalStakeLamports", getU64Decoder()],
    ["clusterSupportPctMinBps", getU64Decoder()],
    ["discussionEpochs", getU64Decoder()],
    ["votingEpochs", getU64Decoder()],
    ["snapshotEpochExtension", getU64Decoder()],
    ["snapshotSlotOffset", getI64Decoder()],
    ["maxSupporters", getU32Decoder()],
  ]);
}

export function getInitializeConfigInstructionDataCodec(): FixedSizeCodec<
  InitializeConfigInstructionDataArgs,
  InitializeConfigInstructionData
> {
  return combineCodec(
    getInitializeConfigInstructionDataEncoder(),
    getInitializeConfigInstructionDataDecoder(),
  );
}

export type InitializeConfigAsyncInput<
  TAccountAdmin extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountProgram extends string = string,
  TAccountProgramData extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  globalConfig?: Address<TAccountGlobalConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  program?: Address<TAccountProgram>;
  programData: Address<TAccountProgramData>;
  maxTitleLength: InitializeConfigInstructionDataArgs["maxTitleLength"];
  maxDescriptionLength: InitializeConfigInstructionDataArgs["maxDescriptionLength"];
  maxSupportEpochs: InitializeConfigInstructionDataArgs["maxSupportEpochs"];
  minProposalStakeLamports: InitializeConfigInstructionDataArgs["minProposalStakeLamports"];
  clusterSupportPctMinBps: InitializeConfigInstructionDataArgs["clusterSupportPctMinBps"];
  discussionEpochs: InitializeConfigInstructionDataArgs["discussionEpochs"];
  votingEpochs: InitializeConfigInstructionDataArgs["votingEpochs"];
  snapshotEpochExtension: InitializeConfigInstructionDataArgs["snapshotEpochExtension"];
  snapshotSlotOffset: InitializeConfigInstructionDataArgs["snapshotSlotOffset"];
  maxSupporters: InitializeConfigInstructionDataArgs["maxSupporters"];
};

export async function getInitializeConfigInstructionAsync<
  TAccountAdmin extends string,
  TAccountGlobalConfig extends string,
  TAccountSystemProgram extends string,
  TAccountProgram extends string,
  TAccountProgramData extends string,
  TProgramAddress extends Address = typeof SVMGOV_PROGRAM_PROGRAM_ADDRESS,
>(
  input: InitializeConfigAsyncInput<
    TAccountAdmin,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountProgram,
    TAccountProgramData
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeConfigInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountProgram,
    TAccountProgramData
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SVMGOV_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    programData: { value: input.programData ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await findGlobalConfigPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU" as Address<"govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("program", accounts.program),
      getAccountMeta("programData", accounts.programData),
    ],
    data: getInitializeConfigInstructionDataEncoder().encode(
      args as InitializeConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeConfigInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountProgram,
    TAccountProgramData
  >);
}

export type InitializeConfigInput<
  TAccountAdmin extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountProgram extends string = string,
  TAccountProgramData extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  globalConfig: Address<TAccountGlobalConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  program?: Address<TAccountProgram>;
  programData: Address<TAccountProgramData>;
  maxTitleLength: InitializeConfigInstructionDataArgs["maxTitleLength"];
  maxDescriptionLength: InitializeConfigInstructionDataArgs["maxDescriptionLength"];
  maxSupportEpochs: InitializeConfigInstructionDataArgs["maxSupportEpochs"];
  minProposalStakeLamports: InitializeConfigInstructionDataArgs["minProposalStakeLamports"];
  clusterSupportPctMinBps: InitializeConfigInstructionDataArgs["clusterSupportPctMinBps"];
  discussionEpochs: InitializeConfigInstructionDataArgs["discussionEpochs"];
  votingEpochs: InitializeConfigInstructionDataArgs["votingEpochs"];
  snapshotEpochExtension: InitializeConfigInstructionDataArgs["snapshotEpochExtension"];
  snapshotSlotOffset: InitializeConfigInstructionDataArgs["snapshotSlotOffset"];
  maxSupporters: InitializeConfigInstructionDataArgs["maxSupporters"];
};

export function getInitializeConfigInstruction<
  TAccountAdmin extends string,
  TAccountGlobalConfig extends string,
  TAccountSystemProgram extends string,
  TAccountProgram extends string,
  TAccountProgramData extends string,
  TProgramAddress extends Address = typeof SVMGOV_PROGRAM_PROGRAM_ADDRESS,
>(
  input: InitializeConfigInput<
    TAccountAdmin,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountProgram,
    TAccountProgramData
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeConfigInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountGlobalConfig,
  TAccountSystemProgram,
  TAccountProgram,
  TAccountProgramData
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SVMGOV_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
    programData: { value: input.programData ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.program.value) {
    accounts.program.value =
      "govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU" as Address<"govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("globalConfig", accounts.globalConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("program", accounts.program),
      getAccountMeta("programData", accounts.programData),
    ],
    data: getInitializeConfigInstructionDataEncoder().encode(
      args as InitializeConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeConfigInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountGlobalConfig,
    TAccountSystemProgram,
    TAccountProgram,
    TAccountProgramData
  >);
}

export type ParsedInitializeConfigInstruction<
  TProgram extends string = typeof SVMGOV_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    globalConfig: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
    program: TAccountMetas[3];
    programData: TAccountMetas[4];
  };
  data: InitializeConfigInstructionData;
};

export function parseInitializeConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      globalConfig: getNextAccount(),
      systemProgram: getNextAccount(),
      program: getNextAccount(),
      programData: getNextAccount(),
    },
    data: getInitializeConfigInstructionDataDecoder().decode(instruction.data),
  };
}
