/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getBallotDecoder,
  getBallotEncoder,
  getBallotTallyDecoder,
  getBallotTallyEncoder,
  getOperatorVoteDecoder,
  getOperatorVoteEncoder,
  type Ballot,
  type BallotArgs,
  type BallotTally,
  type BallotTallyArgs,
  type OperatorVote,
  type OperatorVoteArgs,
} from "../types";

export const BALLOT_BOX_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  155, 169, 156, 8, 92, 14, 24, 101,
]);

export function getBallotBoxDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(BALLOT_BOX_DISCRIMINATOR);
}

export type BallotBox = {
  discriminator: ReadonlyUint8Array;
  /** Bump seed for the PDA */
  bump: number;
  /** The epoch this ballot box is for */
  epoch: bigint;
  /** Slot when this ballot box was created */
  slotCreated: bigint;
  /** Slot when consensus was reached */
  slotConsensusReached: bigint;
  /** Min. percentage of votes required to finalize for this ballot box. */
  minConsensusThresholdBps: number;
  /** The ballot that got at least min_consensus_threshold of votes */
  winningBallot: Ballot;
  /** Operator votes */
  operatorVotes: Array<OperatorVote>;
  /**
   * Vote counts per distinct ballot. Each whitelisted operator contributes
   * one vote; tallies are not stake-weighted.
   */
  ballotTallies: Array<BallotTally>;
  /**
   * Timestamp when voting ends. Tie breaker admin will decide the results
   * if no consensus is reached by then.
   */
  voteExpiryTimestamp: bigint;
  /** Slot for which the snapshot is taken */
  snapshotSlot: bigint;
  /** Snapshot of whitelisted operators at BallotBox creation */
  voterList: Array<Address>;
  /** Whether consensus was reached via tie breaker */
  tieBreakerConsensus: boolean;
};

export type BallotBoxArgs = {
  /** Bump seed for the PDA */
  bump: number;
  /** The epoch this ballot box is for */
  epoch: number | bigint;
  /** Slot when this ballot box was created */
  slotCreated: number | bigint;
  /** Slot when consensus was reached */
  slotConsensusReached: number | bigint;
  /** Min. percentage of votes required to finalize for this ballot box. */
  minConsensusThresholdBps: number;
  /** The ballot that got at least min_consensus_threshold of votes */
  winningBallot: BallotArgs;
  /** Operator votes */
  operatorVotes: Array<OperatorVoteArgs>;
  /**
   * Vote counts per distinct ballot. Each whitelisted operator contributes
   * one vote; tallies are not stake-weighted.
   */
  ballotTallies: Array<BallotTallyArgs>;
  /**
   * Timestamp when voting ends. Tie breaker admin will decide the results
   * if no consensus is reached by then.
   */
  voteExpiryTimestamp: number | bigint;
  /** Slot for which the snapshot is taken */
  snapshotSlot: number | bigint;
  /** Snapshot of whitelisted operators at BallotBox creation */
  voterList: Array<Address>;
  /** Whether consensus was reached via tie breaker */
  tieBreakerConsensus: boolean;
};

/** Gets the encoder for {@link BallotBoxArgs} account data. */
export function getBallotBoxEncoder(): Encoder<BallotBoxArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["bump", getU8Encoder()],
      ["epoch", getU64Encoder()],
      ["slotCreated", getU64Encoder()],
      ["slotConsensusReached", getU64Encoder()],
      ["minConsensusThresholdBps", getU16Encoder()],
      ["winningBallot", getBallotEncoder()],
      ["operatorVotes", getArrayEncoder(getOperatorVoteEncoder())],
      ["ballotTallies", getArrayEncoder(getBallotTallyEncoder())],
      ["voteExpiryTimestamp", getI64Encoder()],
      ["snapshotSlot", getU64Encoder()],
      ["voterList", getArrayEncoder(getAddressEncoder())],
      ["tieBreakerConsensus", getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: BALLOT_BOX_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link BallotBox} account data. */
export function getBallotBoxDecoder(): Decoder<BallotBox> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["bump", getU8Decoder()],
    ["epoch", getU64Decoder()],
    ["slotCreated", getU64Decoder()],
    ["slotConsensusReached", getU64Decoder()],
    ["minConsensusThresholdBps", getU16Decoder()],
    ["winningBallot", getBallotDecoder()],
    ["operatorVotes", getArrayDecoder(getOperatorVoteDecoder())],
    ["ballotTallies", getArrayDecoder(getBallotTallyDecoder())],
    ["voteExpiryTimestamp", getI64Decoder()],
    ["snapshotSlot", getU64Decoder()],
    ["voterList", getArrayDecoder(getAddressDecoder())],
    ["tieBreakerConsensus", getBooleanDecoder()],
  ]);
}

/** Gets the codec for {@link BallotBox} account data. */
export function getBallotBoxCodec(): Codec<BallotBoxArgs, BallotBox> {
  return combineCodec(getBallotBoxEncoder(), getBallotBoxDecoder());
}

export function decodeBallotBox<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<BallotBox, TAddress>;
export function decodeBallotBox<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<BallotBox, TAddress>;
export function decodeBallotBox<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<BallotBox, TAddress> | MaybeAccount<BallotBox, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBallotBoxDecoder(),
  );
}

export async function fetchBallotBox<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<BallotBox, TAddress>> {
  const maybeAccount = await fetchMaybeBallotBox(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBallotBox<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<BallotBox, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBallotBox(maybeAccount);
}

export async function fetchAllBallotBox(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<BallotBox>[]> {
  const maybeAccounts = await fetchAllMaybeBallotBox(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBallotBox(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<BallotBox>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeBallotBox(maybeAccount));
}
