/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getMetaMerkleLeafDecoder,
  getMetaMerkleLeafEncoder,
  type MetaMerkleLeaf,
  type MetaMerkleLeafArgs,
} from "../types";

export const META_MERKLE_PROOF_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([130, 55, 141, 26, 195, 58, 18, 178]);

export function getMetaMerkleProofDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    META_MERKLE_PROOF_DISCRIMINATOR,
  );
}

export type MetaMerkleProof = {
  discriminator: ReadonlyUint8Array;
  /** Payer wallet */
  payer: Address;
  /** ConsensusResult proof is created for. */
  consensusResult: Address;
  /** Meta merkle leaf */
  metaMerkleLeaf: MetaMerkleLeaf;
  /** Meta merkle proof */
  metaMerkleProof: Array<ReadonlyUint8Array>;
  /**
   * Timestamp after which MetaMerkleProof can be closed permissionlessly.
   * This is selected by the payer but our recommendation is to set to vote expiry time.
   */
  closeTimestamp: bigint;
};

export type MetaMerkleProofArgs = {
  /** Payer wallet */
  payer: Address;
  /** ConsensusResult proof is created for. */
  consensusResult: Address;
  /** Meta merkle leaf */
  metaMerkleLeaf: MetaMerkleLeafArgs;
  /** Meta merkle proof */
  metaMerkleProof: Array<ReadonlyUint8Array>;
  /**
   * Timestamp after which MetaMerkleProof can be closed permissionlessly.
   * This is selected by the payer but our recommendation is to set to vote expiry time.
   */
  closeTimestamp: number | bigint;
};

/** Gets the encoder for {@link MetaMerkleProofArgs} account data. */
export function getMetaMerkleProofEncoder(): Encoder<MetaMerkleProofArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["payer", getAddressEncoder()],
      ["consensusResult", getAddressEncoder()],
      ["metaMerkleLeaf", getMetaMerkleLeafEncoder()],
      [
        "metaMerkleProof",
        getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32)),
      ],
      ["closeTimestamp", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: META_MERKLE_PROOF_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link MetaMerkleProof} account data. */
export function getMetaMerkleProofDecoder(): Decoder<MetaMerkleProof> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["payer", getAddressDecoder()],
    ["consensusResult", getAddressDecoder()],
    ["metaMerkleLeaf", getMetaMerkleLeafDecoder()],
    ["metaMerkleProof", getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32))],
    ["closeTimestamp", getI64Decoder()],
  ]);
}

/** Gets the codec for {@link MetaMerkleProof} account data. */
export function getMetaMerkleProofCodec(): Codec<
  MetaMerkleProofArgs,
  MetaMerkleProof
> {
  return combineCodec(getMetaMerkleProofEncoder(), getMetaMerkleProofDecoder());
}

export function decodeMetaMerkleProof<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<MetaMerkleProof, TAddress>;
export function decodeMetaMerkleProof<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<MetaMerkleProof, TAddress>;
export function decodeMetaMerkleProof<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  Account<MetaMerkleProof, TAddress> | MaybeAccount<MetaMerkleProof, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMetaMerkleProofDecoder(),
  );
}

export async function fetchMetaMerkleProof<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<MetaMerkleProof, TAddress>> {
  const maybeAccount = await fetchMaybeMetaMerkleProof(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMetaMerkleProof<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<MetaMerkleProof, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMetaMerkleProof(maybeAccount);
}

export async function fetchAllMetaMerkleProof(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<MetaMerkleProof>[]> {
  const maybeAccounts = await fetchAllMaybeMetaMerkleProof(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMetaMerkleProof(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<MetaMerkleProof>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeMetaMerkleProof(maybeAccount),
  );
}
