export const GET_ALL_PROPOSALS = "GET_ALL_PROPOSALS";
export const GET_VOTE_ACCOUNTS = "GET_VOTE_ACCOUNTS";
export const GET_DEPRECATED_VOTE_ACCOUNTS = "GET_DEPRECATED_VOTE_ACCOUNTS";
export const GET_VALIDATOR_PROPOSAL_VOTE_ACCOUNTS =
  "GET_VALIDATOR_PROPOSAL_VOTE_ACCOUNTS";
export const GET_WALLET_VOTE_OVERRIDE_ACCOUNTS =
  "GET_WALLET_VOTE_OVERRIDE_ACCOUNTS";
export const GET_WALLET_SUPPORT_ACCOUNTS = "GET_WALLET_SUPPORT_ACCOUNTS";
export const GET_USER_HAS_VOTED = "GET_USER_HAS_VOTED";
export const GET_VALIDATOR_HAS_VOTED = "GET_VALIDATOR_HAS_VOTED";
export const GET_USER_HAS_SUPPORTED = "GET_USER_HAS_SUPPORTED";
export const GET_STAKE_ACCOUNTS = "GET_STAKE_ACCOUNTS";
export const GET_DELEGATED_STAKE_ACCOUNTS = "GET_DELEGATED_STAKE_ACCOUNTS";
export const GET_EPOCH_INFO = "GET_EPOCH_INFO";
export const GET_GOVERNANCE_CONFIG = "GET_GOVERNANCE_CONFIG";
