/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export async function findProgramConfigPda(
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU" as Address<"govYkyQ3ePtGULAtY6V75qjWE8UH4vCUVQ1W4HdCAZU">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([
          80, 114, 111, 103, 114, 97, 109, 67, 111, 110, 102, 105, 103,
        ]),
      ),
    ],
  });
}
