/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { NCN_SNAPSHOT_PROGRAM_ADDRESS } from "../programs";

export const FINALIZE_PROPOSED_AUTHORITY_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([89, 96, 108, 130, 223, 223, 213, 102]);

export function getFinalizeProposedAuthorityDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    FINALIZE_PROPOSED_AUTHORITY_DISCRIMINATOR,
  );
}

export type FinalizeProposedAuthorityInstruction<
  TProgram extends string = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountProgramConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountProgramConfig extends string
        ? WritableAccount<TAccountProgramConfig>
        : TAccountProgramConfig,
      ...TRemainingAccounts,
    ]
  >;

export type FinalizeProposedAuthorityInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type FinalizeProposedAuthorityInstructionDataArgs = {};

export function getFinalizeProposedAuthorityInstructionDataEncoder(): FixedSizeEncoder<FinalizeProposedAuthorityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: FINALIZE_PROPOSED_AUTHORITY_DISCRIMINATOR,
    }),
  );
}

export function getFinalizeProposedAuthorityInstructionDataDecoder(): FixedSizeDecoder<FinalizeProposedAuthorityInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getFinalizeProposedAuthorityInstructionDataCodec(): FixedSizeCodec<
  FinalizeProposedAuthorityInstructionDataArgs,
  FinalizeProposedAuthorityInstructionData
> {
  return combineCodec(
    getFinalizeProposedAuthorityInstructionDataEncoder(),
    getFinalizeProposedAuthorityInstructionDataDecoder(),
  );
}

export type FinalizeProposedAuthorityInput<
  TAccountAuthority extends string = string,
  TAccountProgramConfig extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  programConfig: Address<TAccountProgramConfig>;
};

export function getFinalizeProposedAuthorityInstruction<
  TAccountAuthority extends string,
  TAccountProgramConfig extends string,
  TProgramAddress extends Address = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
>(
  input: FinalizeProposedAuthorityInput<
    TAccountAuthority,
    TAccountProgramConfig
  >,
  config?: { programAddress?: TProgramAddress },
): FinalizeProposedAuthorityInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountProgramConfig
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_SNAPSHOT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    programConfig: { value: input.programConfig ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("programConfig", accounts.programConfig),
    ],
    data: getFinalizeProposedAuthorityInstructionDataEncoder().encode({}),
    programAddress,
  } as FinalizeProposedAuthorityInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountProgramConfig
  >);
}

export type ParsedFinalizeProposedAuthorityInstruction<
  TProgram extends string = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    programConfig: TAccountMetas[1];
  };
  data: FinalizeProposedAuthorityInstructionData;
};

export function parseFinalizeProposedAuthorityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedFinalizeProposedAuthorityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { authority: getNextAccount(), programConfig: getNextAccount() },
    data: getFinalizeProposedAuthorityInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
