/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findProgramConfigPda } from "../pdas";
import { NCN_SNAPSHOT_PROGRAM_ADDRESS } from "../programs";

export const INIT_PROGRAM_CONFIG_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([185, 54, 237, 229, 219, 179, 109, 20]);

export function getInitProgramConfigDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_PROGRAM_CONFIG_DISCRIMINATOR,
  );
}

export type InitProgramConfigInstruction<
  TProgram extends string = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountProgramConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountProgramConfig extends string
        ? WritableAccount<TAccountProgramConfig>
        : TAccountProgramConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitProgramConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  svmgovProgramPubkey: Address;
};

export type InitProgramConfigInstructionDataArgs = {
  svmgovProgramPubkey: Address;
};

export function getInitProgramConfigInstructionDataEncoder(): FixedSizeEncoder<InitProgramConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["svmgovProgramPubkey", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_PROGRAM_CONFIG_DISCRIMINATOR }),
  );
}

export function getInitProgramConfigInstructionDataDecoder(): FixedSizeDecoder<InitProgramConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["svmgovProgramPubkey", getAddressDecoder()],
  ]);
}

export function getInitProgramConfigInstructionDataCodec(): FixedSizeCodec<
  InitProgramConfigInstructionDataArgs,
  InitProgramConfigInstructionData
> {
  return combineCodec(
    getInitProgramConfigInstructionDataEncoder(),
    getInitProgramConfigInstructionDataDecoder(),
  );
}

export type InitProgramConfigAsyncInput<
  TAccountPayer extends string = string,
  TAccountAuthority extends string = string,
  TAccountProgramConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  authority: TransactionSigner<TAccountAuthority>;
  programConfig?: Address<TAccountProgramConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  svmgovProgramPubkey: InitProgramConfigInstructionDataArgs["svmgovProgramPubkey"];
};

export async function getInitProgramConfigInstructionAsync<
  TAccountPayer extends string,
  TAccountAuthority extends string,
  TAccountProgramConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
>(
  input: InitProgramConfigAsyncInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountProgramConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitProgramConfigInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountAuthority,
    TAccountProgramConfig,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_SNAPSHOT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    programConfig: { value: input.programConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.programConfig.value) {
    accounts.programConfig.value = await findProgramConfigPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("programConfig", accounts.programConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitProgramConfigInstructionDataEncoder().encode(
      args as InitProgramConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitProgramConfigInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountAuthority,
    TAccountProgramConfig,
    TAccountSystemProgram
  >);
}

export type InitProgramConfigInput<
  TAccountPayer extends string = string,
  TAccountAuthority extends string = string,
  TAccountProgramConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  authority: TransactionSigner<TAccountAuthority>;
  programConfig: Address<TAccountProgramConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  svmgovProgramPubkey: InitProgramConfigInstructionDataArgs["svmgovProgramPubkey"];
};

export function getInitProgramConfigInstruction<
  TAccountPayer extends string,
  TAccountAuthority extends string,
  TAccountProgramConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
>(
  input: InitProgramConfigInput<
    TAccountPayer,
    TAccountAuthority,
    TAccountProgramConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitProgramConfigInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountAuthority,
  TAccountProgramConfig,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_SNAPSHOT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    programConfig: { value: input.programConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("programConfig", accounts.programConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitProgramConfigInstructionDataEncoder().encode(
      args as InitProgramConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitProgramConfigInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountAuthority,
    TAccountProgramConfig,
    TAccountSystemProgram
  >);
}

export type ParsedInitProgramConfigInstruction<
  TProgram extends string = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    authority: TAccountMetas[1];
    programConfig: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitProgramConfigInstructionData;
};

export function parseInitProgramConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitProgramConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      authority: getNextAccount(),
      programConfig: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitProgramConfigInstructionDataDecoder().decode(instruction.data),
  };
}
