/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getNonNullResolvedInstructionInput,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findBallotBoxPda } from "../pdas";
import { NCN_SNAPSHOT_PROGRAM_ADDRESS } from "../programs";

export const INIT_BALLOT_BOX_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array(
  [164, 20, 45, 213, 67, 43, 193, 212],
);

export function getInitBallotBoxDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_BALLOT_BOX_DISCRIMINATOR,
  );
}

export type InitBallotBoxInstruction<
  TProgram extends string = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountProposal extends string | AccountMeta<string> = string,
  TAccountBallotBox extends string | AccountMeta<string> = string,
  TAccountProgramConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountProposal extends string
        ? ReadonlySignerAccount<TAccountProposal> &
            AccountSignerMeta<TAccountProposal>
        : TAccountProposal,
      TAccountBallotBox extends string
        ? WritableAccount<TAccountBallotBox>
        : TAccountBallotBox,
      TAccountProgramConfig extends string
        ? ReadonlyAccount<TAccountProgramConfig>
        : TAccountProgramConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitBallotBoxInstructionData = {
  discriminator: ReadonlyUint8Array;
  snapshotSlot: bigint;
  proposalSeed: bigint;
  splVoteAccount: Address;
};

export type InitBallotBoxInstructionDataArgs = {
  snapshotSlot: number | bigint;
  proposalSeed: number | bigint;
  splVoteAccount: Address;
};

export function getInitBallotBoxInstructionDataEncoder(): FixedSizeEncoder<InitBallotBoxInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["snapshotSlot", getU64Encoder()],
      ["proposalSeed", getU64Encoder()],
      ["splVoteAccount", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_BALLOT_BOX_DISCRIMINATOR }),
  );
}

export function getInitBallotBoxInstructionDataDecoder(): FixedSizeDecoder<InitBallotBoxInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["snapshotSlot", getU64Decoder()],
    ["proposalSeed", getU64Decoder()],
    ["splVoteAccount", getAddressDecoder()],
  ]);
}

export function getInitBallotBoxInstructionDataCodec(): FixedSizeCodec<
  InitBallotBoxInstructionDataArgs,
  InitBallotBoxInstructionData
> {
  return combineCodec(
    getInitBallotBoxInstructionDataEncoder(),
    getInitBallotBoxInstructionDataDecoder(),
  );
}

export type InitBallotBoxAsyncInput<
  TAccountPayer extends string = string,
  TAccountProposal extends string = string,
  TAccountBallotBox extends string = string,
  TAccountProgramConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  /**
   * Verifies the signer is a Proposal PDA from the svmgov program recorded in
   * `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
   * the proposal's seeds) can open a ballot box.
   */
  proposal: TransactionSigner<TAccountProposal>;
  ballotBox?: Address<TAccountBallotBox>;
  programConfig: Address<TAccountProgramConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  snapshotSlot: InitBallotBoxInstructionDataArgs["snapshotSlot"];
  proposalSeed: InitBallotBoxInstructionDataArgs["proposalSeed"];
  splVoteAccount: InitBallotBoxInstructionDataArgs["splVoteAccount"];
};

export async function getInitBallotBoxInstructionAsync<
  TAccountPayer extends string,
  TAccountProposal extends string,
  TAccountBallotBox extends string,
  TAccountProgramConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
>(
  input: InitBallotBoxAsyncInput<
    TAccountPayer,
    TAccountProposal,
    TAccountBallotBox,
    TAccountProgramConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitBallotBoxInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountProposal,
    TAccountBallotBox,
    TAccountProgramConfig,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_SNAPSHOT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    proposal: { value: input.proposal ?? null, isWritable: false },
    ballotBox: { value: input.ballotBox ?? null, isWritable: true },
    programConfig: { value: input.programConfig ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.ballotBox.value) {
    accounts.ballotBox.value = await findBallotBoxPda({
      snapshotSlot: getNonNullResolvedInstructionInput(
        "snapshotSlot",
        args.snapshotSlot,
      ),
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("proposal", accounts.proposal),
      getAccountMeta("ballotBox", accounts.ballotBox),
      getAccountMeta("programConfig", accounts.programConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitBallotBoxInstructionDataEncoder().encode(
      args as InitBallotBoxInstructionDataArgs,
    ),
    programAddress,
  } as InitBallotBoxInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountProposal,
    TAccountBallotBox,
    TAccountProgramConfig,
    TAccountSystemProgram
  >);
}

export type InitBallotBoxInput<
  TAccountPayer extends string = string,
  TAccountProposal extends string = string,
  TAccountBallotBox extends string = string,
  TAccountProgramConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  /**
   * Verifies the signer is a Proposal PDA from the svmgov program recorded in
   * `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
   * the proposal's seeds) can open a ballot box.
   */
  proposal: TransactionSigner<TAccountProposal>;
  ballotBox: Address<TAccountBallotBox>;
  programConfig: Address<TAccountProgramConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  snapshotSlot: InitBallotBoxInstructionDataArgs["snapshotSlot"];
  proposalSeed: InitBallotBoxInstructionDataArgs["proposalSeed"];
  splVoteAccount: InitBallotBoxInstructionDataArgs["splVoteAccount"];
};

export function getInitBallotBoxInstruction<
  TAccountPayer extends string,
  TAccountProposal extends string,
  TAccountBallotBox extends string,
  TAccountProgramConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
>(
  input: InitBallotBoxInput<
    TAccountPayer,
    TAccountProposal,
    TAccountBallotBox,
    TAccountProgramConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitBallotBoxInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountProposal,
  TAccountBallotBox,
  TAccountProgramConfig,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? NCN_SNAPSHOT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    proposal: { value: input.proposal ?? null, isWritable: false },
    ballotBox: { value: input.ballotBox ?? null, isWritable: true },
    programConfig: { value: input.programConfig ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("proposal", accounts.proposal),
      getAccountMeta("ballotBox", accounts.ballotBox),
      getAccountMeta("programConfig", accounts.programConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitBallotBoxInstructionDataEncoder().encode(
      args as InitBallotBoxInstructionDataArgs,
    ),
    programAddress,
  } as InitBallotBoxInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountProposal,
    TAccountBallotBox,
    TAccountProgramConfig,
    TAccountSystemProgram
  >);
}

export type ParsedInitBallotBoxInstruction<
  TProgram extends string = typeof NCN_SNAPSHOT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    /**
     * Verifies the signer is a Proposal PDA from the svmgov program recorded in
     * `ProgramConfig.svmgov_program_pubkey` — only that program (via CPI with
     * the proposal's seeds) can open a ballot box.
     */
    proposal: TAccountMetas[1];
    ballotBox: TAccountMetas[2];
    programConfig: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: InitBallotBoxInstructionData;
};

export function parseInitBallotBoxInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitBallotBoxInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      proposal: getNextAccount(),
      ballotBox: getNextAccount(),
      programConfig: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitBallotBoxInstructionDataDecoder().decode(instruction.data),
  };
}
